name: Update and PR

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-and-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Run update script
        run: bash update.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Automated update"
          branch: "auto/update-$(date +'%Y%m%d')"
          title: "Automated update ($(date +'%Y-%m-%d'))"
          body: "This PR was created automatically by GitHub Actions running update.sh."
