name: Update and PR

permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-and-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Run update script
        run: bash update.sh

      - name: Set Branch Name
        id: set_branch
        run: echo "BRANCH_NAME=auto/update-$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Automated update via update.sh"
          branch: ${{ env.BRANCH_NAME }}
          title: "Automated update (${{ env.BRANCH_NAME }})"
          body: "This PR was created automatically by GitHub Actions"
          token: ${{ secrets.GITHUB_TOKEN }}
